### ISSUE TITLE
Invalid characters when searching by album ID

### ISSUE THREAD

**Issue by Renari** [jellyfin/jellyfin-plugin-vgmdb#22]
```
[2024-02-15 00:39:05.328 -05:00] [ERR] [39] MediaBrowser.Providers.Manager.ProviderManager: Provider "VGMdb" failed to retrieve search results
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 1 | BytePositionInLine: 4.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 1 | BytePositionInLine: 4.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.VgmdbApi.GetSearchResultsAsync(String name, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.Providers.Info.VgmdbAlbumProvider.GetSearchResults(AlbumInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
   ```

**Comment by Formula-9** [comment]
I've looked into it a bit after setting up the plugin on my end and getting similar errors, seems to be because VGMdb.info is reporting a high amount of 503 errors, and serves a HTML page when it happens. According to the issues on their GitHub repo, they seem to say that it's likely that they're being rate-limited by VGMdb.net

**Comment by Renari** [comment]
It looks like this was potentially fixed upstream?

Relevant links:
https://github.com/hufman/vgmdb/issues/81

**Comment by dxman** [comment]
Encountered this same exception when searching for an album artist by ID, so it appears to still be an issue.

Jellyfin v10.9.7, running in Docker, plugin v4.0.0.0

**Comment by Renari** [comment]
https://github.com/hufman/vgmdb/issues/83

**Comment by Reinachan** [comment]
I also encountered this issue. It seemed to cause a lot of issues for me across all of Jellyfin. It seems this crashed scans which resulted in a lot of stuff not being updated. The moment I removed the plugin and did a new scan, all of the newly added genres to the music (I added a lot of genres to indicate game series) suddenly appeared.

**Comment by adetter** [comment]
Encountered this, how do i fix this?

```[2025-11-04 05:33:28.995 +03:00] [ERR] Error in "VGMdb"
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.VgmdbApi.GetSearchResultsAsync(String name, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.Providers.Info.VgmdbArtistProvider.GetSearchResults(ArtistInfo searchInfo, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.Providers.Info.VgmdbArtistProvider.GetIdAsync(ArtistInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Vgmdb.Providers.Info.VgmdbArtistProvider.GetMetadata(ArtistInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)```

**Comment by Renari** [comment]
I'm telling you just disable the plugin, the API is basically unusable it's been that way for 2 years.

**Comment by IMNdi** [comment]
> I'm telling you just disable the plugin

I'm not the kind of person to just take advice blindly so I had a look around and about and upstream and ... yeah, you're right, it's not worth the effort.

I've killed the plugin and my server started running well again.
